name: Shiftleft 

on:
  push:
    branches: ["development"]

  workflow_dispatch:
env:
  SPECTRAL_DSN: ${{ secrets.SPECTRAL_DSN }}

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install and run Spectral CI
      with:
        spectral-dsn: 
        spectral-args: scan --ok
