# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    docker pull checkpoint/shiftleft
    docker run -e "SHIFTLEFT_REGION=eu1" -e "CHKP_CLOUDGUARD_ID=$(CHKP_CLOUDGUARD_ID)" -e "CHKP_CLOUDGUARD_SECRET=$(CHKP_CLOUDGUARD_SECRET)" checkpoint/shiftleft git clone https://github.com/CHASourcecom/Shiftleft_Az_Pipeline.git && shiftleft code-scan -s ./Shiftleft_Az_Pipeline
  displayName: 'Shiftleft Code-Scan'
